[node]
owner_id = ""
name = "keyston-node-01"
port = 5000
host = "0.0.0.0"
registration_interval = 10
heartbeat_interval = 30
ipfs_host = "http://localhost:5001"
data_path = "/app/data"

[satellite]
api_host = "http://satellite:8000"
peer_host = "satellite"
peer_port = 4001
peer_id = ""
